ALTER TABLE roles
    ALTER COLUMN name TYPE VARCHAR(30),
    ALTER COLUMN description TYPE VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN email TYPE VARCHAR(100),
    ALTER COLUMN name TYPE VARCHAR(100),
    ALTER COLUMN google_id TYPE VARCHAR(100);

ALTER TABLE epics
    ALTER COLUMN name TYPE VARCHAR(100);

ALTER TABLE sprints
    ALTER COLUMN name TYPE VARCHAR(100),
    ALTER COLUMN goal TYPE VARCHAR(255);

ALTER TABLE task_statuses
    ALTER COLUMN name TYPE VARCHAR(30);

ALTER TABLE task_priorities
    ALTER COLUMN name TYPE VARCHAR(30);

ALTER TABLE tasks
    ALTER COLUMN title TYPE VARCHAR(150);