spring:
  application:
    name: task-management
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagement
    username: postgres
    password: DatabaseConnection
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /

security:
  jwt:
    secret: ${JWT_SECRET:supersecretkeysupersecretkeysupersecretkeysupersecretkey}
    token-validity-in-seconds: 86400
  oauth2:
    google:
      client-id: ${GOOGLE_CLIENT_ID:731870641465-2m1plh852jj6rubpq403i8cjs7521k2u.apps.googleusercontent.com}

logging:
  level:
    org.springframework: INFO
    com.taskmanagement: DEBUG
